# Generated by Django 5.1.4 on 2025-05-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_achievements_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
