# Generated by Django 5.1.4 on 2025-05-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое название совета', max_length=100)),
                ('icon', models.ImageField(help_text='Минималистичная иконка для совета', upload_to='tips/icons/')),
                ('text', models.TextField(help_text='Полный текст совета')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в ленте')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
